name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: 🛠️ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: 📦 Install dependencies
        run: yarn install
      - name: ☢️ Biome
        run: yarn biome ci
      - name: 🧪 Test
        run: yarn test
      - name: 🔨 Build
        run: yarn build
      - name: 🚀 Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            main.js
            manifest.json
            styles.css
